name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://transfer.sh/(RECOMMENDED)'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt install -y git wget lz4 tar openssl python3 python3-pip

    - name: Install AVBTool dependencies
      run: |
        pip3 install pycryptodome

    - name: Fetch image from URL
      run: |
        echo "Downloading from: ${{ github.event.inputs.RECOVERY_URL }}"
        wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img
        ls -lh recovery.img

    - name: Patch Process-1
      run: |
        chmod +x script1.sh magiskboot
        ./script1.sh || true

    - name: Patch Process-2
      run: |
        chmod +x script2.sh
        ./script2.sh || true
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c < recovery.img) \
          --image recovery-patched.img \
          --key phh.pem \
          --algorithm SHA256_RSA4096

        mkdir -p output
        mv recovery-patched.img output/recovery.img
        cd output
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5
        cd ..

    - name: Upload Recovery
      uses: actions/upload-artifact@v4
      with:
        path: output/fastbootd-recovery.tar.md5
        name: Patched-Recovery
