name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'URL to recovery.img (.img or .img.lz4)'
        required: true
        default: 'https://example.com/recovery.img'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget lz4 openssl python3 python3-pip
          pip3 install pycryptodome

      - name: Debug Inputs
        run: echo "Input URL: ${{ github.event.inputs.RECOVERY_URL }}"

      - name: Download Recovery
        run: |
          wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img || wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img.lz4
          ls -lh

      - name: Run script1.sh
        run: |
          chmod +x script1.sh
          chmod +x magiskboot
          ./script1.sh

      - name: Run script2.sh
        run: |
          chmod +x script2.sh
          ./script2.sh

      - name: Sign Patched Recovery
        run: |
          python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
          python3 avbtool add_hash_footer \
            --partition_name recovery \
            --partition_size $(wc -c < recovery.img) \
            --image recovery-patched.img \
            --key phh.pem \
            --algorithm SHA256_RSA4096

      - name: Package Output
        run: |
          mkdir -p output
          mv recovery-patched.img output/recovery.img
          cd output
          tar cvf fastbootd-recovery.tar recovery.img
          md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
          mv fastbootd-recovery.tar fastbootd-recovery.tar.md5
          cd ..

      - name: Upload Patched Recovery
        uses: actions/upload-artifact@v4
        with:
          name: Patched-Recovery
          path: output/fastbootd-recovery.tar.md5
